### ISSUE TITLE
SvgConverter/ConverterLogic.GetClipElement is using global XPath expr instead of local

### ISSUE THREAD

**Issue by Arlorean** [BerndK/SvgToXaml#1]
ConverterLogic.cs:614:

            var clipElement = drawingGroupElement.XPathSelectElement("//defns:DrawingGroup.ClipGeometry", _nsManager);

This should start with "." otherwise it's searching for ClipGeometry in the entire document not relative to the current DrawingGroup.

            var clipElement = drawingGroupElement.XPathSelectElement(".//defns:DrawingGroup.ClipGeometry", _nsManager);

**Comment by BerndK** [comment]
fixed, thanks for your comment Arlorean.
