### ISSUE TITLE
Mixed usage of comma (,) and dot (.)

### ISSUE THREAD

**Issue by knappema** [BerndK/SvgToXaml#11]
Generated Xaml:
            \<DrawingGroup ClipGeometry="M0,0 H779,52753 V667,20471 H0 V0 Z"\>
but should be:
            \<DrawingGroup ClipGeometry="M0,0 H779.52753 V667.20471 H0 V0 Z"\>

The CultureInfo should be always en-US.
So the following lines are missing in the App.xaml.cs:
            System.Threading.Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US", false);
            System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US", false);

**Comment by BerndK** [comment]
Right.
Fixed see [commit](https://github.com/BerndK/SvgToXaml/commit/6e95dc4348e3aedb0785092956fa84a97ad93a30)
Thanks for reporting, Bernd.
