### ISSUE TITLE
Cannot build solution

### ISSUE THREAD

**Issue by link1375** [BerndK/SvgToXaml#17]
I downloaded the .zip and opened the solution in VS 2019. The solution explorer tells me that SvgToXaml was unloaded. If I build the solution I get two errors:
1) 'GlyphRun' does not contain a definition for 'PixelsPerDip' (ConverterLogic.cs line 508)
2) Metadata file ...\SvgToXaml-master\SvgConverter\bin\Debug\SvgConverter.dll' could not be found

**Comment by silviubogan** [comment]
In case it helps, I solved the error (1) by installing .NET Framework 4.6.2.

**Comment by silviubogan** [comment]
Now I get the error (2) on another computer and I do not know what to do to use the program on that computer. The `WpfDemoApp` works well though.

Screenshot with the error:

![devenv_2019-09-03_08-19-38](https://user-images.githubusercontent.com/198924/64146058-1819cf80-ce24-11e9-9463-c33a00ba4861.png)

Text of the error in the Output pane (showing output from Build):

```
1>------ Build started: Project: SvgToXaml, Configuration: Debug Any CPU ------
1>CSC : error CS0006: Metadata file 'C:\...\git\SvgToXaml\SvgConverter\bin\Debug\SvgConverter.dll' could not be found
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
