### ISSUE TITLE
Stop crashing when showing svgz files, or even display them like svg files

### ISSUE THREAD

**Issue by silviubogan** [BerndK/SvgToXaml#18]
Thank you.

**Comment by BerndK** [comment]
I had no crashes when trying to show svgz files.
Anyway I added support for compressed files.
Please test latest sources.

**Comment by silviubogan** [comment]
On the computer where I have built the project successfully, I see that this issue is solved.

Thank you.

I do not know about the other computer until #17 is solved.

**Comment by silviubogan** [comment]
I copied the Release binaries on the second computer, I run them and I see that this issue is really solved. Thank you.
