### ISSUE TITLE
Can I use this lib to convert SVG to PNG in a UWP App?

### ISSUE THREAD

**Issue by JohnTortugo** [BerndK/SvgToXaml#2]

**Comment by BerndK** [comment]
Hi Divino,

yes this should be possible.
use
_convertedObj = ConverterLogic.ConvertSvgToObject(_filepath, 
ResultMode.DrawingImage, null, out _objectName, new ResKeyInfo()) as 
DependencyObject;

then see here to convert DrawinImage to png: 
http://stackoverflow.com/questions/14387350/convert-drawingimage-to-bitmapimage

If all this works on UWP, I'm not sure about that.

Am 02.03.2016 um 18:56 schrieb Divino César:
