### ISSUE TITLE
viewBox not considered if stroke is in path

### ISSUE THREAD

**Issue by Dave220** [BerndK/SvgToXaml#20]
If there is a "viewBox" in svg file, the SvgToXaml converter does not consider the relative coordinates of e.g. a "path", if there is a "stroke" defined in that "path". This is only done if there is a no "stroke" defined inside the "path" object in svg file.
What happens is:
In first case the convertrer produces e.g.:</br> 
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;GeometryDrawing Brush="#FFE68686" Geometry="{StaticResource testGeometry1}"&gt;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;GeometryDrawing.Pen&gt;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;Pen Brush="#FFE6E6E6" Thickness="2" StartLineCap="Flat" EndLineCap="Flat" LineJoin="Miter" MiterLimit="10" /&gt;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/GeometryDrawing.Pen&gt;
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;/GeometryDrawing&gt;</br>
In second case the convertre produces e.g.:</br>
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;GeometryDrawing Brush="#FFE6E6E6" Geometry="{StaticResource testGeometry2}" /&gt;</br>
The problem could be solved, if for the svg "viewBox" e.g.: viewBox="0 0 120 120"
an additional line of e.g.:</br>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;GeometryDrawing Brush="Black" Geometry="F1 M120,120z M0,0z" /&gt;</br>
would be added by the converter.

**Comment by BerndK** [comment]
Thanks for the feedback, but I did not get the problem.
Can you provide a sample svg?
(btw I can't promise to fix it)

**Comment by BerndK** [comment]
Closed due to long inactivity and not provided sample file.
