### ISSUE TITLE
There are extra lines in the picture conversion

### ISSUE THREAD

**Issue by qiu770** [BerndK/SvgToXaml#21]
HI

In the conversion to the picture is more than some interference line

![image](https://user-images.githubusercontent.com/14813805/95543594-853a6400-0a2b-11eb-823e-df1f0db0ec36.png)

this is source image 
![image](https://user-images.githubusercontent.com/14813805/95543663-bca91080-0a2b-11eb-92f7-74fe4703b09a.png)

**Comment by BerndK** [comment]
Hi,
not sure what the problem is here.
Maybe there are some 'incorrect' or non-conform setting in the source file.
The tool is primarily designed to convert svg-icons to .net wpf objects on a batch basis.
If you need to convert a single file, consider the use of another tool like inkscape.

**Comment by BerndK** [comment]
Closed due to long inactivity.
