### ISSUE TITLE
Build failed: 'GlyphRun' does not contain a definition for 'PixelsPerDip'

### ISSUE THREAD

**Issue by cregx** [BerndK/SvgToXaml#22]
When I try to compile the project SvgToXaml I get the following error message: 'GlyphRun' does not contain a definition for 'PixelsPerDip'.

**Comment by BerndK** [comment]
Try to install and use .Net 4.6.2 or newer like 4.7.x
does this help?
or use the precompiled one, see releases

**Comment by BerndK** [comment]
Closed, is a
Duplicate of #24
