### ISSUE TITLE
Prebuilt binaries?

### ISSUE THREAD

**Issue by sommmen** [BerndK/SvgToXaml#23]
Hi,

Are there also prebuilt binaries, so i don't have to download the whole project?

**Comment by BerndK** [comment]
just look here:
https://github.com/BerndK/SvgToXaml/releases

**Comment by sommmen** [comment]
Ah I see thanks. I think the release tab moved at some point in the github Ui or something. I was looking in the wrong place.  Anyways thanks and sorry for the obvious question.On Dec 10, 2020 11:12 PM, Bernd Klaiber <notifications@github.com> wrote:
Closed #23.
