### ISSUE TITLE
How to use in code behind

### ISSUE THREAD

**Issue by hupo376787** [BerndK/SvgToXaml#27]
Hi, I found we can use in xaml like:
`<Image Source="{StaticResource cloud_3_iconDrawingImage}"/>`
But how to use in code behind,thanks.

**Comment by BerndK** [comment]
Hi,
this is a general .net topic which is not really related to SvgToXaml, please use another platform like stackoverflow for this.

**Comment by hupo376787** [comment]
Thanks, bro. I found it. https://stackoverflow.com/questions/14387350/convert-drawingimage-to-bitmapimage
