### ISSUE TITLE
Add option to upload svg through raw text / change color of the svg

### ISSUE THREAD

**Issue by Pauldb-Levarne** [BerndK/SvgToXaml#31]
Hi,

I would like an option to convert raw svg text to a .xaml file. For example

````
<svg width="99" height="81" viewBox="0 0 99 81" fill="none" xmlns="http://www.w3.org/2000/svg">
...
</svg>
````

Also an option to change the path color of the svgs that are uploaded to a certain color.

Anyway,

Great work!

**Comment by BerndK** [comment]
Hi,
the use case is to give support to a developer when designing icons based on SVGs. So you can view/analyze a SVG and see the resulting xaml code that can be used. There is also a batch process using the application with parameters to convert a directory of multiple files.
For changing the color there is an example in the demo project,
