### ISSUE TITLE
Text is not always recognized in SVG

### ISSUE THREAD

**Issue by aaronnottbeck** [BerndK/SvgToXaml#32]
First: Thank you very much for this nice helpful tool.

I have som svg files where i have the problem that the result xaml path does not contain the text existing in the original.
I tried to investigate the original files to find a difference in the text description but everything looks okay for me. 

In my explorer the extension renders everything and also in FireFox.

![Excel_Export](https://user-images.githubusercontent.com/3070852/187924636-83f26469-e17e-4f9f-9df3-8071790050aa.svg)
![RIB_Import_DataFromTXT](https://user-images.githubusercontent.com/3070852/187924641-47c072ba-d8f6-4b70-ae34-3293fe3e271d.svg)
[test.xaml.txt](https://github.com/BerndK/SvgToXaml/files/9470174/test.xaml.txt)

**Comment by aaronnottbeck** [comment]
i debugged the code and the problem occures in SharpVectors

**Comment by paulushub** [comment]
> i debugged the code and the problem occures in SharpVectors

The app is using a version of the SharpVectors released in 2018!

**Comment by aaronnottbeck** [comment]
yes i know. ther for i updated the whole application to net6.0 and the last sharpvector package but the problem resists.
However now i'm using the test app of sharpvector. no need to do anything.
