### ISSUE TITLE
Support for UWP

### ISSUE THREAD

**Issue by MajidAbuRmelah** [BerndK/SvgToXaml#33]
Hey,

First, I would like to say that your tool is very helpful and useful, I have been using a lot this year.
I was wondering if you have something similar that can be directly implemented into UWP, that would be amazing.

Regards,
Majid Abu Rmila

**Comment by BerndK** [comment]
Sorry, I'm not a pro on using UWP. No idea what changes needs to be made for UWP, so I can't support this right now.
