### ISSUE TITLE
Show neon effect

### ISSUE THREAD

**Issue by Sadness96** [BerndK/SvgToXaml#34]
Now there are some neon SVG, Gaussian blur can not be converted into code to display.
![Monster](https://user-images.githubusercontent.com/19670054/197782754-1d71afd6-996b-4374-ba20-46c14fdea456.svg)
<img width="265" alt="image" src="https://user-images.githubusercontent.com/19670054/197783634-ebcf9e64-1904-4053-bcf6-986c8bd331cd.png">

**Comment by BerndK** [comment]
Hi,
the goal of SVGToXaml is to convert the path (and perhaps the text) of a simple SVG to WPF's Path Geometry. The conversion is not that simple than converting a bmp to jpg. SVG has more options than WPF, or they are more compley to achieve. So 'glow' is an example for that. This is not supported here, sorry.
You will need to search for other solutions in WPF.
