### ISSUE TITLE
18 Errors in solution

### ISSUE THREAD

**Issue by Cossack13** [BerndK/SvgToXaml#5]
1x Cannot find the static member 'JOGGeometry1Key' on the type 'Icons'.
\SvgToXaml-master\WpfDemoApp\Images\Icons.xaml
+
17x The name "Icons" does not exist in the namespace "clr-namespace:WpfDemoApp.Images".
WpfDemoApp	...\SvgToXaml-master\WpfDemoApp\Images\Icons.xaml

**Comment by BerndK** [comment]
Please try to checkout again! I fixed the wrong names.

Am 17.01.2017 um 10:12 schrieb Ilya:
