### ISSUE TITLE
The BKEDV nuget package is no longer available

### ISSUE THREAD

**Issue by StingyJack** [BerndK/SvgToXaml#7]
So compiling this no longer works. 
![image](https://cloud.githubusercontent.com/assets/15381181/25526523/dde9939a-2be1-11e7-92a8-291b83c3f655.png)

https://libraries.io/nuget/BKEDV.CommandLineParser

**Comment by BerndK** [comment]
The package is not available via nuget, but it i checked in: https://github.com/BerndK/SvgToXaml/blob/master/packages/BKEDV.CommandLineParser.1.0.4.0/BKEDV.CommandLineParser.1.0.4.0.nupkg
So this should work!?

**Comment by StingyJack** [comment]
Oh. I have my packages folder pointing to a common location so it wasnt picking this up. You may want to add a nuget config to hint at this folder.

**Comment by BerndK** [comment]
The package is defined in the csproj-file together with a relative hint to the packages folder. So my VisualStudio finds everything without problems.

**Comment by StingyJack** [comment]
Im having other package management problems with vs 2017, so it's probably my machine.

Outlook's new Clutter feature is crap


________________________________

**Comment by BerndK** [comment]
Ok, thanks for the info.
I developed this with VS2015, but tested it regarding your complaint 
with a new installed VS2017. Both without problems.

regards, Bernd.

Am 09.05.2017 um 14:54 schrieb Andrew Stanton:
