### ISSUE TITLE
MatrixTransform and 2 more Issues

### ISSUE THREAD

**Issue by Bardaky** [BerndK/SvgToXaml#8]
Hello,

I am having several issues with a xaml created by your wonderful application.
I am running a fresh WPF application that I inserted the created xaml file into and merged the resourcedictionary into the standard window resources.

I have MatrixTransform elements that complain about having direct content.
<MatrixTransform>1,0,0,1,0,63.500003</MatrixTransform>
 "The type "MatrixTransform" does not support direct content."

Somehow it cannot find something from sharpvectors?
<svg:EmbeddedBitmapSource Data="......"/>
"The name "EmbeddedBitmapSource" does not exist in the namespace "https://sharpvectors.codeplex.com/runtime/"."

The GlyphRunt has no such thing called "PixelsPerDip".
<GlyphRun PixelsPerDip="1"....../>
"The member PixeslPerDip" is not recognized or is not accessible."

**Comment by BerndK** [comment]
Sorry, never experienced that.
SVG has a ton of features, some of them cannot be converted automatically.
Consider to convert your SVG first, perhaps using free app InkScape

regards, Bernd.
