### ISSUE TITLE
Are hyperlinks active in XAML?

### ISSUE THREAD

**Issue by ksmiller99** [BerndK/SvgToXaml#9]
I have an application that generates SVG files on demand with hyperlinks to a custom protocol inside them. I'd rather display them natively in my than launching MSIE (apparently on MSIE supports launching custom protocols from an SVG) Are the hyperlinks in the converted SVG active?

**Comment by BerndK** [comment]
Hi,
I don't think that this is supported in WPF.
If you need this functionality, you would have to implement this festure as a link when the user clicks on you image/button.
reagrds, Bernd.

PS: sorry for late answer.
